# Generated by Django 2.1.7 on 2019-05-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190514_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
